services:
  challenges:
    image: app-challenges
  flashcards:
    image: app-flashcards
  notes:
    image: app-notes
  users:
    image: app-users
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3500/api/health || exit 1
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 5s
  gateway:
    image: app-gateway
    depends_on:
      users:
        condition: service_healthy
        restart: true
        required: true
      challenges:
        condition: service_started
        restart: true
        required: true
      flashcards:
        condition: service_started
        restart: true
        required: true
      notes:
        condition: service_started
        restart: true
        required: true
    ports:
      - "3500:3500"
