services:
  challenges:
    image: app-challenges
  flashcards:
    image: app-flashcards
  notes:
    image: app-notes
  users:
    image: app-users
  gateway:
    image: app-gateway
    depends_on:
      - challenges
      - flashcards
      - notes
      - users
    ports:
      - "3500:3500"
