services:
  challenges:
    image: app-challenges
  flashcards:
    image: app-flashcards
  notes:
    image: app-notes
  users:
    image: app-users
  gateway:
    image: app-gateway
    depends_on:
      users:
        condition: service_started
        restart: true
        required: true
      challenges:
        condition: service_started
        restart: true
        required: true
      flashcards:
        condition: service_started
        restart: true
        required: true
      notes:
        condition: service_started
        restart: true
        required: true
    ports:
      - "3500:3500"
